### ISSUE TITLE
Please provide the tests files in your releases

### ISSUE THREAD

**Issue by P-EB** [rbarrois/volatildap#3]
Hi,

I'm currently packaging volatildap into Debian.

As the tests are something useful to ensure along time that a package properly works, I had to rebuild a tarball from your release one in order to include the tests directory.

Could you consider providing all the tests scripts in your next release, please? :)

Cheers!

**Comment by rbarrois** [comment]
Which tarball was missing the tests?

I'd say that:
- They should be included in the .tar.gz
- They must be excluded from the wheels

Including the tests & Makefile in the tarball without installing them can be tricky — but that is required, otherwise we'd get conflicts between all the projets whose tests are located in ``tests/`` ;)

**Comment by P-EB** [comment]
https://pypi.debian.net/volatildap/volatildap-1.1.0.tar.gz, which is a clone of the pypi.python.org tarballl.

**Comment by rbarrois** [comment]
OK, I think I see how we went into this. I'll have to fix the ``MANIFEST.in`` and adjust the ``setup.py`` accordingly.

By the way, does the Debian project provide guidelines as to "what a Python package developer should do to ease its packaging by Debian"? I'm sure such a document would be very useful for both educating Python developers and helping Debian maintainers when explaining what is required :-)

Such document could include hints on the various keywords expected in the ``MANIFEST.in`` or the ``setup.py``, for instance.

**Comment by P-EB** [comment]
Thanks!

Regarding your question, I think the current answer is "no". But the question is legitimate, and I'm eager to try forwarding it to the python team. :)

Oh, and by the way, I'll have to submit the same issue on django-ldapdb. :P

**Comment by P-EB** [comment]
@rbarrois can you think about adding the `tests` directory for the next release? :)
