### ISSUE TITLE
[Debian] Could you add the copyright years to your license file?

### ISSUE THREAD

**Issue by P-EB** [rbarrois/volatildap#4]
Another minor query : your License file is pretty good, as it helps to determine wether I can package your software into debian, but it'd be better if you put the copyright years next to your name. :)

**Comment by rbarrois** [comment]
What is the value of adding those years? In my experience, as a developer, they force me to add a meaningless commit once a year.
=> Is there a reference document explaining what is required or not here?

I'd rather avoid it altogether — a possible compromise would be to only change that year in the License file itself.

**Comment by P-EB** [comment]
It fits the BSD 2 Clause license template (see https://opensource.org/licenses/BSD-2-Clause ), and allows a better understanding about how recent the work is, and how long the software did get maintained in d/copyright.

It can be useful to infer the relevance of a package.

**Comment by dekkers** [comment]
Consensus in Debian is that yearless copyright statements are fine so this bug can be closed: https://lists.debian.org/debian-devel/2023/02/msg00234.html

**Comment by P-EB** [comment]
It's not that simple.

https://lists.debian.org/debian-devel/2023/02/msg00242.html
https://lists.debian.org/debian-devel/2023/02/msg00244.html

While copyright information are legally optional, it's still relevant to have some if possible. In particular it implicitely also gives vision on how some work falls into public domain.

Anyway, I'll remove volatildap from Debian so this problem is moot.
